modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/More-Search-Bars/issues"
license = "MIT"

[[mods]]
modId = "moresearchbars"
version = "${version}"
displayName = "More Search Bars"
authors = "CoolAid48"

description = '''
Add more search bars to various UI screens
'''

logoFile = "assets/moresearchbars/icon.png"

[[mixins]]
config = "moresearchbars.neoforge.mixins.json"
